include:
  - ./docker-compose-base.yml

# To ensure that the container processes the locally modified `service_conf.yaml.template` instead of the one included in its image, you need to mount the local `service_conf.yaml.template` to the container.
services:
  ragflow:
    depends_on:
      mysql-ragflow:
        condition: service_healthy
      redis-ragflow:
        condition: service_healthy
          #es01:
          #  condition: service_healthy
          #minio-ragflow:
          #condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    container_name: ragflow-server
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          #count: all
    #          device_ids: ['0','1']
    #          capabilities: [gpu]
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 9980:9980
      - 443:443
      - 5678:5678
      - 5679:5679
      - 9382:9382
    volumes:
      - /opt/ragflow/logs:/ragflow/logs
      - ./certs/ca.crt:/ragflow/ca.crt
      - ../rag:/ragflow/rag
      - ../tests:/ragflow/tests
      - ../api:/ragflow/api
      - ../minerU:/ragflow/minerU
       #- /root/.cache:/root/.cache
       #- /root/magic-pdf.json:/root/magic-pdf.json
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragflow/history_data_agent
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragflow/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragflow/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    devices:
      - /dev/davinci1:/dev/davinci4
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=4
    networks:
      ragflow:
        ipv4_address: 172.20.0.254
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

  executor-1:
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-executor-1
    volumes:
      - /opt/ragflow/logs:/ragflow/logs
      - ./certs/ca.crt:/ragflow/ca.crt
      - ../rag:/ragflow/rag
      - ../tests:/ragflow/tests
      - ../api:/ragflow/api
      - ../minerU:/ragflow/minerU
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragflow/history_data_agent
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragflow/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragflow/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=5
    entrypoint: "/ragflow/entrypoint.sh --disable-webserver --workers=1 --host-id=executor-1"
    devices:
      - /dev/davinci2:/dev/davinci5
    networks:
      - ragflow
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

  executor-2:
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-executor-2
    volumes:
      - /opt/ragflow/logs:/ragflow/logs
      - ./certs/ca.crt:/ragflow/ca.crt
      - ../rag:/ragflow/rag
      - ../tests:/ragflow/tests
      - ../api:/ragflow/api
      - ../minerU:/ragflow/minerU
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragflow/history_data_agent
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragflow/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragflow/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=6
    entrypoint: "/ragflow/entrypoint.sh --disable-webserver --workers=1 --host-id=executor-2"
    devices:
      - /dev/davinci3:/dev/davinci6
    networks:
      - ragflow
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
