include:
  - ./docker-compose-base.yml

# To ensure that the container processes the locally modified `service_conf.yaml.template` instead of the one included in its image, you need to mount the local `service_conf.yaml.template` to the container.
services:
  ragforge:
    depends_on:
      mysql-ragforge:
        condition: service_healthy
      redis-ragforge:
        condition: service_healthy
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
          #minio-ragforge:
          #condition: service_healthy
    image: ${RAGFORGE_IMAGE}
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    container_name: ragforge-server
    entrypoint: "/ragforge/entrypoint.sh --disable-taskexecutor --host-id=api"
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          #count: all
    #          device_ids: ['0','1']
    #          capabilities: [gpu]
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 9980:9980
      - 443:443
      - 5678:5678
      - 5679:5679
      - 9382:9382
    volumes:
      - /opt/coredumps:/opt/coredumps
      - /opt/ragforge/logs:/ragforge/logs
      - ./certs/ca.crt:/ragforge/ca.crt
      - ../rag:/ragforge/rag
      - ../tests:/ragforge/tests
      - ../web:/ragforge/web
      - ../api:/ragforge/api
      - ../minerU:/ragforge/minerU
       #- /root/.cache:/root/.cache
       #- /root/magic-pdf.json:/root/magic-pdf.json
      - ./nginx/ragforge.conf:/etc/nginx/conf.d/ragforge.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragforge/history_data_agent
      - ./service_conf.yaml.template:/ragforge/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragforge/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragforge/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    devices:
      - /dev/davinci4:/dev/davinci4
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=4
    networks:
      ragforge:
        ipv4_address: 172.20.0.254
    restart: on-failure
    extra_hosts:
      - "minio-ragforge:172.20.0.250"
      - "minio-ragforge-backup:172.20.0.251"
      - "host.docker.internal:host-gateway"

  executor-0:
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    image: ${RAGFORGE_IMAGE}
    container_name: ragforge-executor-0
    volumes:
      - /opt/coredumps:/opt/coredumps
      - /opt/ragforge/logs:/ragforge/logs
      - ./certs/ca.crt:/ragforge/ca.crt
      - ../rag:/ragforge/rag
      - ../tests:/ragforge/tests
      - ../api:/ragforge/api
      - ../minerU:/ragforge/minerU
      - ./nginx/ragforge.conf:/etc/nginx/conf.d/ragforge.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragforge/history_data_agent
      - ./service_conf.yaml.template:/ragforge/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragforge/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragforge/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=4
    entrypoint: "/ragforge/entrypoint.sh --disable-webserver --workers=1 --host-id=executor-0"
    devices:
      - /dev/davinci4:/dev/davinci4
    networks:
      - ragforge
    restart: on-failure
    extra_hosts:
      - "minio-ragforge:172.20.0.250"
      - "minio-ragforge-backup:172.20.0.251"
      - "host.docker.internal:host-gateway"

  executor-1:
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    image: ${RAGFORGE_IMAGE}
    container_name: ragforge-executor-1
    volumes:
      - /opt/coredumps:/opt/coredumps
      - /opt/ragforge/logs:/ragforge/logs
      - ./certs/ca.crt:/ragforge/ca.crt
      - ../rag:/ragforge/rag
      - ../tests:/ragforge/tests
      - ../api:/ragforge/api
      - ../minerU:/ragforge/minerU
      - ./nginx/ragforge.conf:/etc/nginx/conf.d/ragforge.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragforge/history_data_agent
      - ./service_conf.yaml.template:/ragforge/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragforge/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragforge/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=5
    entrypoint: "/ragforge/entrypoint.sh --disable-webserver --workers=1 --host-id=executor-1"
    devices:
      - /dev/davinci5:/dev/davinci5
    networks:
      - ragforge
    restart: on-failure
    extra_hosts:
      - "minio-ragforge:172.20.0.250"
      - "minio-ragforge-backup:172.20.0.251"
      - "host.docker.internal:host-gateway"

  executor-2:
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    image: ${RAGFORGE_IMAGE}
    container_name: ragforge-executor-2
    volumes:
      - /opt/coredumps:/opt/coredumps
      - /opt/ragforge/logs:/ragforge/logs
      - ./certs/ca.crt:/ragforge/ca.crt
      - ../rag:/ragforge/rag
      - ../tests:/ragforge/tests
      - ../api:/ragforge/api
      - ../minerU:/ragforge/minerU
      - ./nginx/ragforge.conf:/etc/nginx/conf.d/ragforge.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragforge/history_data_agent
      - ./service_conf.yaml.template:/ragforge/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragforge/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragforge/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=6
    entrypoint: "/ragforge/entrypoint.sh --disable-webserver --workers=1 --host-id=executor-2"
    devices:
      - /dev/davinci6:/dev/davinci6
    networks:
      - ragforge
    restart: on-failure
    extra_hosts:
      - "minio-ragforge:172.20.0.250"
      - "minio-ragforge-backup:172.20.0.251"
      - "host.docker.internal:host-gateway"

  executor-3:
    user: root
    privileged: true
    ipc: host
    shm_size: '128gb'
    image: ${RAGFORGE_IMAGE}
    container_name: ragforge-executor-3
    volumes:
      - /opt/coredumps:/opt/coredumps
      - /opt/ragforge/logs:/ragforge/logs
      - ./certs/ca.crt:/ragforge/ca.crt
      - ../rag:/ragforge/rag
      - ../tests:/ragforge/tests
      - ../api:/ragforge/api
      - ../minerU:/ragforge/minerU
      - ./nginx/ragforge.conf:/etc/nginx/conf.d/ragforge.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/private.key:/etc/nginx/private.key
      - ./nginx/public.crt:/etc/nginx/public.crt
      - ../history_data_agent:/ragforge/history_data_agent
      - ./service_conf.yaml.template:/ragforge/conf/service_conf.yaml.template
      - ./s3.py:/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/python3.10/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/usr/local/lib/python3.10/dist-packages/magic_pdf/data/io/s3.py
      - ./s3.py:/root/miniconda3/lib/python3.10/site-packages/magic_pdf/data/io/s3.py
      - ./_client.py:/ragforge/.venv/lib/python3.10/site-packages/httpx/_client.py
      - ../conf/llm_factories.json:/ragforge/conf/llm_factories.json
      - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - LM_TIMEOUT_SECONDS=300
      - LLM_MAX_RETRIES=3
      # 设置默认数据库类型为达梦
      - DB_TYPE=dm
      - ASCEND_RT_VISIBLE_DEVICES=7
    entrypoint: "/ragforge/entrypoint.sh --disable-webserver --workers=1 --host-id=executor-3"
    devices:
      - /dev/davinci7:/dev/davinci7
    networks:
      - ragforge
    restart: on-failure
    extra_hosts:
      - "minio-ragforge:172.20.0.250"
      - "minio-ragforge-backup:172.20.0.251"
      - "host.docker.internal:host-gateway"
