include:
  - ./docker-compose-base.yml

# To ensure that the container processes the locally modified `service_conf.yaml.template` instead of the one included in its image, you need to mount the local `service_conf.yaml.template` to the container.
services:
  ragflow:
    depends_on:
      mysql-ragflow:
        condition: service_healthy
      redis-ragflow:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: all
              device_ids: ['4','5','6','7']
              capabilities: [gpu]
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
      - 5678:5678
      - 5679:5679
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - /var/lib/gpustack/ragflow/ragflow/api/apps/kb_app.py:/ragflow/api/apps/kb_app.py
      - /var/lib/gpustack/ragflow/ragflow/rag/app/paper.py:/ragflow/rag/app/paper.py
      - /var/lib/gpustack/ragflow/ragflow/rag/svr/task_executor.py:/ragflow/rag/svr/task_executor.py
      - /var/lib/gpustack/ragflow/ragflow/minerU:/ragflow/minerU
      - /var/lib/gpustack/ragflow/ragflow/rag/svr/task_executor.py:/ragflow/rag/svr/task_executor.py
      - /root/.cache:/root/.cache
      - /root//magic-pdf.json:/root//magic-pdf.json
        #- /var/lib/gpustack/ragflow/ragflow/rag/nlp/search.py:/ragflow/rag/nlp/search.py
        #- /var/lib/gpustack/ragflow/ragflow/rag/svr/task_executor.py:/ragflow/rag/svr/task_executor.py
        #- /var/lib/gpustack/ragflow/ragflow/rag/utils/minio_conn.py:/ragflow/rag/utils/minio_conn.py
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../history_data_agent:/ragflow/history_data_agent
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template

    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
        #- CUDA_VISIBLE_DEVICES=1
        #- NCCL_SOCKET_IFNAME=bond0.128
        #- NCCL_IB_DISABLE=1
        #- NCCL_P2P_DISABLE=1
        #- NCCL_DEBUG=INFO
    networks:
      - ragflow
    restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
        #executor:
        #  depends_on:
        #    mysql:
        #      condition: service_healthy
        #  image: ${RAGFLOW_IMAGE}
        #  container_name: ragflow-executor
        #  volumes:
        #    - ./ragflow-logs:/ragflow/logs
        #    - /var/lib/gpustack/ragflow/ragflow/api/apps/kb_app.py:/ragflow/api/apps/kb_app.py
        #      #- /var/lib/gpustack/ragflow/ragflow/rag/nlp/search.py:/ragflow/rag/nlp/search.py
        #      #- /var/lib/gpustack/ragflow/ragflow/rag/svr/task_executor.py:/ragflow/rag/svr/task_executor.py
        #      #- /var/lib/gpustack/ragflow/ragflow/rag/utils/minio_conn.py:/ragflow/rag/utils/minio_conn.py
        #    - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
        #    - ./nginx/proxy.conf:/etc/nginx/proxy.conf
        #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #  env_file: .env
        #  environment:
        #    - TZ=${TIMEZONE}
        #    - HF_ENDPOINT=${HF_ENDPOINT}
        #    - MACOS=${MACOS}
        #  entrypoint: "/ragflow/entrypoint.sh 1 3"
        #  networks:
        #    - ragflow
        #  restart: on-failure
        #  # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
        #  # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
        #  extra_hosts:
        #    - "host.docker.internal:host-gateway"
